<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>add_item</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1b69249f-11cb-483a-90f4-0fc496c73dd6</testSuiteGuid>
   <testCaseLink>
      <guid>0b814d03-3028-4216-844a-e39ec2ed884c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_add_item/TC_add_0_item</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>276127a0-ba31-4779-b492-cc32fdbc2de1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_add_item/TC_add_1_item</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8e9febf-4f11-4a18-b2ff-96f7a985dfd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71f05943-fd1b-45a9-8231-6d82b92e5516</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96b3b7d6-d003-4a65-9be9-c57b3ff1c0b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_add_item/TC_add_item_exits</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>03ff4c8c-030d-413b-8d33-b7ff13b8fda9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/add_item_exits_data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>03ff4c8c-030d-413b-8d33-b7ff13b8fda9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item_quanlity</value>
         <variableId>d90d9f47-22d9-4cd5-8216-1a07aadeed55</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e8ee76f-fb4e-4306-a946-8b38ee694d77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_add_item/TC_add_100_item</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
