<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>change_password</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>249f4bf7-196e-445f-9fff-0786a8095ca5</testSuiteGuid>
   <testCaseLink>
      <guid>c4780362-b6a9-4499-a56e-fb4ce44cfcdb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_change_password/TC_change_password_failed</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a34234d9-b6c2-4a9b-9a70-a5fdff9d4ff2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/change_password_data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a34234d9-b6c2-4a9b-9a70-a5fdff9d4ff2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>old_password</value>
         <variableId>127f6994-3e36-450f-9a09-521b875f59ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a34234d9-b6c2-4a9b-9a70-a5fdff9d4ff2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>new_password</value>
         <variableId>c572f480-5cf7-4359-b730-cc9cbb580eae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a34234d9-b6c2-4a9b-9a70-a5fdff9d4ff2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>confirm_password</value>
         <variableId>6a794710-d642-4e14-8351-3a1eb7058227</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a34234d9-b6c2-4a9b-9a70-a5fdff9d4ff2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>message</value>
         <variableId>a17f1919-8540-4554-87f2-793fa4657634</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7aecd743-3751-4403-ab05-7a1c3c03d2f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_change_password/TC_change_password_passed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
