<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_đangki_taiday</name>
   <tag></tag>
   <elementGuidId>b30ec3b6-3507-4bdd-932d-7445b6e997f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='signUp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signUp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af502314-7d67-4f5e-92e2-376110d3f665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ghost</value>
      <webElementGuid>0b88b998-0990-4d02-85c6-a4d216f05fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signUp</value>
      <webElementGuid>a11465c6-5fc4-4294-bce3-ad4e4f75b182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng Ký Tại Đây</value>
      <webElementGuid>830bc944-cd31-42e1-9c12-ec10ad340e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signUp&quot;)</value>
      <webElementGuid>79cf687a-f767-481e-ac77-d04a0fa7c6f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='signUp']</value>
      <webElementGuid>75ea7b64-0f33-4cf6-a4e2-f7df7c18cdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[3]/div/div[2]/button</value>
      <webElementGuid>0258a844-ebaa-43e6-9a88-c0e9e1a0ee9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, customer!'])[1]/following::button[1]</value>
      <webElementGuid>70fe9c81-0da7-471f-ac60-d78874be4551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng Nhập Tại Đây'])[1]/following::button[1]</value>
      <webElementGuid>9ce94c48-b270-4106-bfa8-fa7790deb16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng Ký Tại Đây']/parent::*</value>
      <webElementGuid>c6658e4a-b43a-40af-a645-2cb19350e18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>65673801-ddd0-4414-bee3-82cfab320bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'signUp' and (text() = 'Đăng Ký Tại Đây' or . = 'Đăng Ký Tại Đây')]</value>
      <webElementGuid>74c6cd47-90f5-4a7a-9417-e50a98c84b47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
