<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>def3c716-0e2b-44bf-b87e-4496ee0b6b2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usernamelog</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usernamelog']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df2220db-fb0d-447f-81e6-0ca6beae29d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>usernamelog</value>
      <webElementGuid>65fbdccf-2858-4b8d-9be7-aa7c56425378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usernamelog</value>
      <webElementGuid>76da67d2-160c-4ced-bde6-70a2b9360607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0249fae3-eaf9-4497-ba1b-4e78838ca154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tên Đăng Nhập</value>
      <webElementGuid>f55c0e83-e2e0-47dc-a6dc-0a8c77bbffe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usernamelog&quot;)</value>
      <webElementGuid>e7948d91-8af7-4e4b-a7a0-2b10db596a6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usernamelog']</value>
      <webElementGuid>1de74d8e-9452-4f54-bb68-e2d86f6a742c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signinForm']/input</value>
      <webElementGuid>7b4cb82f-8b2c-42d1-85e1-f443fd908edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/input</value>
      <webElementGuid>e621614c-24a2-48de-be88-1c80a62a94fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'usernamelog' and @id = 'usernamelog' and @type = 'text' and @placeholder = 'Tên Đăng Nhập']</value>
      <webElementGuid>3d9a9789-784c-40e2-b33c-d8d9cf756efe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
