<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>8ad91ce1-286d-4fa1-b1b5-9d5e0f04bc64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordlog</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwordlog']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a50cb2d2-2c28-48a5-9235-aa9ed7727941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passwordlog</value>
      <webElementGuid>436b5ea9-bfc6-46f8-93de-c24d69411b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordlog</value>
      <webElementGuid>4fb475dc-972e-4c70-bcc3-d8f6e8bab3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d2fac7f0-3a5f-481f-8813-1866aca0400c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật Khẩu</value>
      <webElementGuid>4b497b24-ef6b-40b2-bd2e-26f548930a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordlog&quot;)</value>
      <webElementGuid>d934650c-100d-4173-8769-e6db25b71deb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwordlog']</value>
      <webElementGuid>46169744-47ff-45ad-824c-6c51eca06888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signinForm']/input[2]</value>
      <webElementGuid>84e848dd-7388-4e26-bbd2-a4db00239e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/input[2]</value>
      <webElementGuid>1c2d7127-b27b-407d-8ea8-91d9ba3348b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'passwordlog' and @id = 'passwordlog' and @type = 'password' and @placeholder = 'Mật Khẩu']</value>
      <webElementGuid>2782638e-b368-4787-bd73-999fb833b3b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
