<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_change_password</name>
   <tag></tag>
   <elementGuidId>dfb8345c-e30b-48ba-8213-85e6f2eb32b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnupdatepassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnupdatepassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e16b7cd2-ce3b-40a4-8739-6f224585c189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad9115c3-402d-48fe-b3b5-e6ba2b2c0b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnupdatepassword</value>
      <webElementGuid>54272b89-fb54-41c6-a4e4-24c03e0b39f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Chỉnh sửa Mật Khẩu</value>
      <webElementGuid>d64f45b7-db17-49f2-9f68-db68e2e1e48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-4 btn btn-secondary mt-4</value>
      <webElementGuid>968d6b48-f3e4-4e68-9bc5-a55e1541da76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>f1d3453d-529f-4a1f-a1e3-1789dbf22311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#exampleModal2</value>
      <webElementGuid>f3b19fd0-cdd6-4041-a271-d9ad4fcc648b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnupdatepassword&quot;)</value>
      <webElementGuid>cd96a993-e416-4b63-bbf4-98784e9b7eca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnupdatepassword']</value>
      <webElementGuid>28bf471f-ee12-412d-a6de-4f8bb5934593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>df778f23-e4b1-4df8-91c7-657313960979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnupdatepassword']</value>
      <webElementGuid>87ccdf32-9bbb-499d-aab2-32aebed92646</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
