<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_confirm_password</name>
   <tag></tag>
   <elementGuidId>d3d0c346-aadb-4c43-9519-c60cf3a36ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfb42ffd-92f4-4d78-b21a-ffaabba1c9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>10f407be-9b20-40eb-975e-cdf0aef264fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmpassword</value>
      <webElementGuid>6f6510db-0c17-4402-8b3e-3e42389a8d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>89a8a2c0-8626-42a6-af97-2000d5b08f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmpassword&quot;)</value>
      <webElementGuid>c6381199-34b7-4a66-9c33-5af9ae54c83b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmpassword']</value>
      <webElementGuid>6d57353f-21a2-48ff-9c60-bdc695a8703f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exampleModal2']/div/div/div[2]/div[3]/input</value>
      <webElementGuid>5bf32183-0b50-4885-b174-66a98bbe0144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>0e560c8e-bf2e-4754-bf85-cb6ed77cfe11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'confirmpassword']</value>
      <webElementGuid>32f376b8-6b20-480e-8dc1-1b62cd9af6bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
