<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_new_password</name>
   <tag></tag>
   <elementGuidId>020948bc-564a-4abd-b2e6-66f15a656d78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6cf6387-6c84-459c-a5ca-c52ad4508424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>63db97cb-4a7e-4ee5-849c-ed7f852317d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newpassword</value>
      <webElementGuid>d82b238d-05f7-40e0-b85d-463c18b7fd75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>161befa2-cfc1-4994-b8d5-5528408c89af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newpassword&quot;)</value>
      <webElementGuid>3375a425-93ad-44f5-ac7e-be031c79c1bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newpassword']</value>
      <webElementGuid>1c0e1cd2-2b9f-4b87-8852-ac019cbc48c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exampleModal2']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>e5925c41-04e0-45b7-91a7-59b862c6b160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>45596775-dbc7-4819-8839-c24a805bf833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'newpassword']</value>
      <webElementGuid>6a9697ce-af0c-4361-a6de-e5950873475a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
