<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_old_password</name>
   <tag></tag>
   <elementGuidId>c6e66fb2-8f42-44cd-a599-9efc4e86a3f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oldpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oldpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5452c31b-8c74-49a1-b6c4-80c93df38939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9172bdcc-51f6-4be4-ada5-2e6fba1c2c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldpassword</value>
      <webElementGuid>bb6a3630-1b8d-40ef-9d44-6efa71f854fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a8b80b4e-3dd4-4653-8341-3452739cbb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldpassword&quot;)</value>
      <webElementGuid>e48a6858-2fe9-4d31-9ae5-fa510876cbc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oldpassword']</value>
      <webElementGuid>105f2c62-6bfb-4be6-abba-1b7352ecde1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exampleModal2']/div/div/div[2]/div/input</value>
      <webElementGuid>aa74f142-4e0c-4d9c-9fe4-f6c96e13ae24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a784559f-fe30-4fce-9d4e-e494104ffbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'oldpassword']</value>
      <webElementGuid>2f72fb28-27b6-48f1-bf43-3024436c67c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
