<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_cart</name>
   <tag></tag>
   <elementGuidId>efcda69f-93b2-413e-87dd-fcd0d7b5cb21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarsFurni']/ul[2]/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.mt-2 > img[alt=&quot;Image&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2c9d25b1-e185-404a-8611-c3e88c37817a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Public/images/cart.svg</value>
      <webElementGuid>dd9ead04-9c39-474a-ad83-98d02c5b28e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Image</value>
      <webElementGuid>4c74202d-3d01-4d74-9cf6-47133ffd0799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarsFurni&quot;)/ul[@class=&quot;custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5&quot;]/li[2]/a[@class=&quot;nav-link mt-2&quot;]/img[1]</value>
      <webElementGuid>8740b3dc-903a-473b-8698-290b158a9bba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarsFurni']/ul[2]/li[2]/a/img</value>
      <webElementGuid>dd04a8a3-e59e-43de-8fec-42766de47738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Image'])[2]</value>
      <webElementGuid>3bf00251-f75d-4cfa-ab9f-f3281066f20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>b686b3e3-a66c-4bb4-8e53-26fde26fcfb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../Public/images/cart.svg' and @alt = 'Image']</value>
      <webElementGuid>336ea7de-d176-4c91-a2da-5388060d80b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
