<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quanlity_item</name>
   <tag></tag>
   <elementGuidId>06bc57c9-20f1-4c34-b544-63ffae1e6d7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-quantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product-quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5c3e33f-50bb-441f-881d-ddbe8608afe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c6f66ee2-1eb8-4f8d-be09-60c084313384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product-quantity</value>
      <webElementGuid>d58ee14d-af57-4fa2-a501-b8bd1fe9d956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-quantity</value>
      <webElementGuid>a162ab00-1e65-4b36-bcd6-e9b883a2b163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-3 form-control-sm text-center</value>
      <webElementGuid>8752e5db-2803-4ff4-9bf9-be7bd66d1b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ccb2a5b5-86bd-423c-931b-f31f1357325d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listcart&quot;)/tr[1]/td[5]/div[@class=&quot;input-group input-group-sm&quot;]/input[@id=&quot;product-quantity&quot;]</value>
      <webElementGuid>50436412-7712-4cce-8a13-85c1d0642e22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product-quantity']</value>
      <webElementGuid>2457bf6b-1c2a-4c27-bcdd-fa6aa214a0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='listcart']/tr/td[5]/div/input</value>
      <webElementGuid>0f9f8618-449e-4424-a0b2-346b71d0a30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/input</value>
      <webElementGuid>4fe0bdb3-3931-4dd2-8b59-197cd65198c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'product-quantity' and @id = 'product-quantity']</value>
      <webElementGuid>a1e90f68-7f7f-44ac-bfc7-2a08ffdce0cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
